name: "Conjur JWT Fetcher dockerless @tudorUrdes"
description: "Fetch secrets from CyberArk Conjur using GitHub OIDC JWT - ARC tested (no audience)"

inputs:
  url:
    description: "Base URL of Conjur, e.g. https://18.130.69.198 or FQDN"
    required: true
  account:
    description: "Conjur account name (e.g. poc-conjur)"
    required: true
  certificate:
    description: "PEM CA certificate for Conjur TLS (optional)"
    required: false
  authn_id:
    description: "authn-jwt/<id> configured in Conjur (e.g. authn-jwt/github)"
    required: true
  secrets:
    description: "Mapping: conjur-path|ENV;conjur-path2|ENV2"
    required: true

runs:
  using: "composite"
  steps:

    # 1) Write CA certificate if provided
    - name: Write CA certificate if provided
      shell: bash
      run: |
        if [ -n "${{ inputs.certificate }}" ]; then
          echo "${{ inputs.certificate }}" > conjur-ca.pem
        fi

    # 2) Get GitHub OIDC Token (NO audience)
    - name: Get OIDC Token
      id: oidc
      shell: bash
      run: |
        set -euo pipefail

        if [ -z "${ACTIONS_ID_TOKEN_REQUEST_URL:-}" ] || [ -z "${ACTIONS_ID_TOKEN_REQUEST_TOKEN:-}" ]; then
          echo "GitHub OIDC env vars not present; ensure permissions.id-token: write"
          exit 1
        fi

        RAW_JSON=$(curl -sS \
          -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}")

        TOKEN=$(printf '%s' "$RAW_JSON" \
          | sed -n 's/.*"value"[ ]*:[ ]*"\([^"]*\)".*/\1/p')

        if [ -z "$TOKEN" ]; then
          echo "Failed to extract OIDC token"
          echo "Raw JSON: $RAW_JSON"
          exit 1
        fi

        echo "OIDC_TOKEN=$TOKEN" >> "$GITHUB_ENV"

    # 3) Authenticate to Conjur via authn-jwt
    
    - name: Authenticate to Conjur
      id: conjur-auth
      shell: bash
      run: |
        set -euo pipefail

        AUTH_URL="${{ inputs.url }}/authn-jwt/${{ inputs.authn_id }}/${{ inputs.account }}/authenticate"

        if [ -f conjur-ca.pem ]; then
          CURL_CA_OPT="--cacert conjur-ca.pem"
        else
          CURL_CA_OPT="-k"   # PoC only
        fi

        # capture raw response
        RAW_TOKEN=$(curl -sS $CURL_CA_OPT \
          -X POST \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "jwt=${OIDC_TOKEN}" \
          "$AUTH_URL")

        # trim newlines / spaces
        CONJUR_TOKEN=$(printf '%s' "$RAW_TOKEN" | tr -d '\r\n ')

        if [ -z "$CONJUR_TOKEN" ]; then
          echo "Failed to authenticate to Conjur via authn-jwt"
          echo "Raw response was: $RAW_TOKEN"
          exit 1
        fi

        echo "CONJUR_TOKEN=$CONJUR_TOKEN" >> "$GITHUB_ENV"


    # 4) Fetch secrets using the mapping
    
    - name: Fetch Conjur secrets
      shell: bash
      run: |
        set -euo pipefail

        if [ -f conjur-ca.pem ]; then
          CURL_CA_OPT="--cacert conjur-ca.pem"
        else
          CURL_CA_OPT="-k"
        fi

        IFS=';' read -ra PAIRS <<< "${{ inputs.secrets }}"

        for pair in "${PAIRS[@]}"; do
          [ -z "$pair" ] && continue

          conjur_var="${pair%%|*}"
          env_name="${pair##*|}"

          encoded=$(printf '%s' "$conjur_var" | sed 's/\//%2F/g')
          SECRET_URL="${{ inputs.url }}/secrets/${{ inputs.account }}/variable/${encoded}"

          TMP_RESP=$(mktemp)
          HTTP_CODE=$(curl -sS $CURL_CA_OPT \
            -o "$TMP_RESP" \
            -w "%{http_code}" \
            -H "Authorization: Token token=\"${CONJUR_TOKEN}\"" \
            "$SECRET_URL")

          BODY=$(cat "$TMP_RESP")
          rm -f "$TMP_RESP"

          if [ "$HTTP_CODE" -ne 200 ]; then
            echo "Failed to fetch $conjur_var (HTTP $HTTP_CODE)"
            echo "Response body:"
            echo "$BODY"
            exit 1
          fi

          # BODY is the secret value
          echo "${env_name}=${BODY}" >> "$GITHUB_ENV"
        done
