name: "Conjur JWT Fetcher Dockerless"
description: "Fetch secrets from CyberArk Conjur using GitHub OIDC JWT, ARC compatible version 0.9"

inputs:
  conjur-url:
    description: "Base URL of Conjur (e.g. https://dns)"
    required: true
  conjur-account:
    description: "Conjur account name"
    required: true
  conjur-authn-id:
    description: "authn-jwt/<id> configured in Conjur"
    required: true
  conjur-ca-cert:
    description: "PEM certificate for TLS (optional)"
    required: false
  audience:
    description: "JWT audience configured in Conjur"
    required: true
  secrets:
    description: "Mapping: conjur-path|ENV;conjur-path|ENV"
    required: true

runs:
  using: "composite"
  steps:

    # --- Write CA cert if provided ---
    - name: Write CA certificate if provided
      shell: bash
      run: |
        if [ -n "${{ inputs.conjur-ca-cert }}" ]; then
          echo "${{ inputs.conjur-ca-cert }}" > conjur-ca.pem
        fi

    # --- Get GitHub OIDC Token ---
    - name: Get OIDC Token
      id: oidc
      shell: bash
      run: |
        set -euo pipefail

        AUD="${{ inputs.audience }}"

        # Request OIDC token from GitHub
        RAW_JSON=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${AUD}" )

        # Extract the value field without jq
        TOKEN=$(printf '%s' "$RAW_JSON" \
          | sed -n 's/.*"value"[ ]*:[ ]*"\([^"]*\)".*/\1/p')

        if [ -z "$TOKEN" ]; then
          echo "Failed to extract OIDC token"
          echo "Raw JSON was: $RAW_JSON"
          exit 1
        fi

        echo "OIDC_TOKEN=$TOKEN" >> "$GITHUB_ENV"

    # --- Authenticate to Conjur via authn-jwt ---
    - name: Authenticate to Conjur
      id: conjur-auth
      shell: bash
      run: |
        set -euo pipefail

        AUTH_URL="${{ inputs.conjur-url }}/authn-jwt/${{ inputs.conjur-authn-id }}/${{ inputs.conjur-account }}/authenticate"
        CURL_CA_ARG=""
        if [ -f conjur-ca.pem ]; then
          CURL_CA_ARG="--cacert conjur-ca.pem"
        else
          CURL_CA_ARG="-k"
        fi

        CONJUR_TOKEN=$(curl -sS $CURL_CA_ARG \
          -X POST \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "jwt=${OIDC_TOKEN}" \
          "$AUTH_URL")

        if [ -z "$CONJUR_TOKEN" ]; then
          echo "Failed to authenticate to Conjur"
          exit 1
        fi

        echo "CONJUR_TOKEN=$CONJUR_TOKEN" >> "$GITHUB_ENV"

    # --- Fetch secrets mapping ---
    - name: Fetch Conjur secrets
      shell: bash
      run: |
        set -euo pipefail

        IFS=';' read -ra PAIRS <<< "${{ inputs.secrets }}"

        for pair in "${PAIRS[@]}"; do
          [ -z "$pair" ] && continue

          conjur_var="${pair%%|*}"
          env_name="${pair##*|}"

          # URL-encode manually (safe for alphanumerics, slash, hyphen)
          encoded=$(printf '%s' "$conjur_var" | sed 's/\//%2F/g')

          SECRET_URL="${{ inputs.conjur-url }}/secrets/${{ inputs.conjur-account }}/variable/${encoded}"

          CURL_CA_ARG=""
          [ -f conjur-ca.pem ] && CURL_CA_ARG="--cacert conjur-ca.pem" || CURL_CA_ARG="-k"

          value=$(curl -sS $CURL_CA_ARG \
            -H "Authorization: Token token=\"${CONJUR_TOKEN}\"" \
            "$SECRET_URL")

          if [ -z "$value" ]; then
            echo "Failed to fetch secret: $conjur_var"
            exit 1
          fi

          echo "$env_name=$value" >> "$GITHUB_ENV"
        done
