name: release
on: [push]

jobs:
  test:
    runs-on: self-hosted
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher Action
        uses: cyberark/conjur-action@v2.0.6
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: ${{ secrets.ACCOUNT }}
          authn_id: ${{ secrets.AUTHN_ID_2 }}
          secrets: data/vault/poc-tud-2025/Database-MySQL-poc-username/username|sql_username;data/vault/poc-tud-2025/Database-MySQL-poc-username/password|sql_password

      - name: step02
        run: |
          echo -n 'Retrieved username [ '
          echo -n $SQL_USERNAME | sed 's/./& /g'
          echo -n '] and password [ '
          echo -n $SQL_PASSWORD | sed 's/./& /g'
          echo '.]'
